"use client";
import { FormEvent, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ShieldCheck } from "lucide-react";
export default function LoginPage() {
  const params = useSearchParams(); const [mode,setMode]=useState<"login"|"register">("login"); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch(`/api/auth/${mode==="login"?"login":"register"}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){setError(result.error??"Não foi possível continuar.");setLoading(false);return}const requested=params.get("returnTo");window.location.href=requested?.startsWith("/")&&!requested.startsWith("//")?requested:result.user.role==="admin"?"/admin":"/conta"}
  return <main className="auth-page"><a href="/"><img src="/highparts-logo.png" alt="HighParts"/></a><section><div className="auth-heading"><small>CONTA HIGHPARTS</small><h1>{mode==="login"?"Bem-vindo de volta.":"Crie sua conta."}</h1><p>Carrinho, veículos e pedidos ficam salvos com segurança.</p></div><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Entrar</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Criar conta</button></div><form onSubmit={submit}>{mode==="register"&&<><label>Nome completo<input name="name" required minLength={2}/></label><label>Telefone<input name="phone" placeholder="(00) 00000-0000"/></label></>}<label>E-mail<input name="email" type="email" required autoComplete="email"/></label><label>Senha<input name="password" type="password" required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"}/></label>{error&&<p className="auth-error">{error}</p>}<button className="auth-submit" disabled={loading}>{loading?"Aguarde...":mode==="login"?"Entrar":"Criar minha conta"}</button></form><div className="auth-secure"><ShieldCheck/><span><b>Sessão protegida</b><small>Senha criptografada e cookie seguro.</small></span></div></section></main>;
}
