"use client";
import { FormEvent, useState } from "react";
import { MailCheck, ShieldCheck } from "lucide-react";

export default function ForgotPasswordPage() {
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [emailError,setEmailError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");setEmailError("");const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const result=await response.json();setLoading(false);if(!response.ok){if(result.fieldErrors?.email)setEmailError(result.fieldErrors.email);else setError(result.error??"Não foi possível continuar.");return}setMessage(result.emailConfigured?"Se existir uma conta com esse e-mail, você receberá um link válido por 30 minutos.":"A recuperação está pronta, mas o envio de e-mail ainda precisa ser configurado pelo administrador.")}
  return <main className="auth-page"><a href="/"><img src="/highparts-logo.png" alt="HighParts"/></a><section><div className="auth-heading"><small>RECUPERAÇÃO DE ACESSO</small><h1>Esqueceu sua senha?</h1><p>Informe o e-mail usado na sua conta.</p></div>{message?<div className="auth-success"><MailCheck/><p>{message}</p><a href="/entrar">Voltar para entrar</a></div>:<form onSubmit={submit} noValidate><label className={emailError?"field-invalid":""}>E-mail<input name="email" type="email" autoComplete="email" onChange={()=>setEmailError("")}/>{emailError&&<small className="field-error">{emailError}</small>}</label>{error&&<p className="auth-error">{error}</p>}<button className="auth-submit" disabled={loading}>{loading?"Enviando...":"Enviar link de recuperação"}</button><a className="auth-back" href="/entrar">Voltar para entrar</a></form>}<div className="auth-secure"><ShieldCheck/><span><b>Solicitação protegida</b><small>Nunca informamos se um e-mail está cadastrado.</small></span></div></section></main>
}
