"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, CircleUserRound, Heart, Menu, PackageCheck, Search, ShieldCheck, ShoppingCart, SlidersHorizontal, Star, Truck, X, Zap } from "lucide-react";
import VehicleFinder from "./vehicle-finder";

type Product = { id:string; name:string; category:string; fit:string; price:number|null; stock:number|null; badge?:string; tone:string };
type ApiProduct = { code:string; product:string; application:string; axle:string; type:string; priceCents:number|null; stockQuantity:number|null };
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function PartVisual({product}:{product:Product}) { return <div className="part" style={{"--tone":product.tone} as React.CSSProperties}><i/><b>{product.category}</b></div> }

export default function Home(){
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todos"); const [products,setProducts]=useState<Product[]>([]); const [catalogLoading,setCatalogLoading]=useState(true); const [cart,setCart]=useState<string[]>([]); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false); const [menu,setMenu]=useState(false); const [user,setUser]=useState<{name:string}|null>(null); const [cartReady,setCartReady]=useState(false);
  useEffect(()=>{(async()=>{const catalog=await fetch("/api/catalog?limit=60").then(r=>r.json() as Promise<{products?:ApiProduct[]}>).catch(()=>({products:[]}));const mapped=(catalog.products||[]).map((p:ApiProduct):Product=>({id:p.code,name:p.product,category:p.type||"Freios",fit:`${p.application}${p.axle?` • ${p.axle}`:""}`,price:p.priceCents==null?null:p.priceCents/100,stock:p.stockQuantity,badge:p.priceCents!=null&&p.stockQuantity&&p.stockQuantity>0?"Disponível":undefined,tone:"#e31b2d"}));setProducts(mapped);setCatalogLoading(false);const local=JSON.parse(localStorage.getItem("highparts_cart")||"[]") as string[];const me=await fetch("/api/auth/me").then(r=>r.json() as Promise<{user:{name:string}|null}>).catch(()=>({user:null}));setUser(me.user);if(me.user){const saved=await fetch("/api/account/cart").then(r=>r.json() as Promise<{items?:Array<{itemKey:string;quantity:number}>}>).catch(()=>({items:[]}));const remote=(saved.items||[]).flatMap((item)=>Array.from({length:item.quantity},()=>String(item.itemKey))).filter((id:string)=>mapped.some((p:Product)=>p.id===id));setCart(remote.length?remote:local.filter(id=>mapped.some((p:Product)=>p.id===id)))}else setCart(local.filter(id=>mapped.some((p:Product)=>p.id===id)));setCartReady(true)})()},[]);
  useEffect(()=>{const receive=(event:Event)=>{const code=(event as CustomEvent<string>).detail;setCategory("Todos");setQuery(code);document.querySelector("#ofertas")?.scrollIntoView({behavior:"smooth"})};window.addEventListener("highparts:search",receive);return()=>window.removeEventListener("highparts:search",receive)},[]);
  useEffect(()=>{if(query.trim().length<2)return;const timer=setTimeout(async()=>{const data=await fetch(`/api/catalog?q=${encodeURIComponent(query.trim())}&limit=60`).then(r=>r.json() as Promise<{products?:ApiProduct[]}>).catch(()=>({products:[]}));const found=(data.products||[]).map((p:ApiProduct):Product=>({id:p.code,name:p.product,category:p.type||"Freios",fit:`${p.application}${p.axle?` • ${p.axle}`:""}`,price:p.priceCents==null?null:p.priceCents/100,stock:p.stockQuantity,badge:p.priceCents!=null&&p.stockQuantity&&p.stockQuantity>0?"Disponível":undefined,tone:"#e31b2d"}));setProducts(current=>[...current,...found.filter(p=>!current.some(c=>c.id===p.id))])},300);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{if(!cartReady)return;localStorage.setItem("highparts_cart",JSON.stringify(cart));if(user){const grouped=[...new Set(cart)].map(id=>{const p=products.find(product=>product.id===id)!;return {itemKey:id,name:p.name,fit:p.fit,priceCents:Math.round((p.price??0)*100),quantity:cart.filter(item=>item===id).length}});fetch("/api/account/cart",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({items:grouped})})}},[cart,cartReady,user,products]);
  const categories=["Todos",...Array.from(new Set(products.map(p=>p.category))).slice(0,6)];
  const filtered=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&`${p.name} ${p.fit}`.toLowerCase().includes(query.toLowerCase())),[query,category]);
  const items=cart.map(id=>products.find(p=>p.id===id)!).filter(Boolean); const subtotal=items.reduce((s,p)=>s+(p.price??0),0);
  if(checkout) return <Checkout items={items} subtotal={subtotal} onBack={()=>setCheckout(false)}/>;
  return <main>
    <div className="topbar"><span>Frete grátis acima de R$ 499 para Sul e Sudeste</span><span>Compra 100% segura</span></div>
    <header className="header"><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button><a href="#inicio"><img className="logo" src="/highparts-logo.png" alt="HighParts"/></a><nav className={menu?"open":""}><a href="#categorias">Categorias</a><a href="#ofertas">Ofertas</a><a href="#compatibilidade">Encontre sua peça</a><a href="#suporte">Suporte</a></nav><div className="header-actions"><a className="admin-link" href={user?"/conta":"/entrar"}><CircleUserRound/> {user?user.name.split(" ")[0]:"Entrar"}</a><button className="cart-icon" onClick={()=>setCartOpen(true)}><ShoppingCart/><b>{cart.length}</b></button></div></header>
    <section className="hero" id="inicio"><div className="hero-copy"><div className="eyebrow"><Zap/> PERFORMANCE COMEÇA NA ESCOLHA CERTA</div><h1>PEÇAS QUE LEVAM<br/>SEU CARRO <em>ALÉM.</em></h1><p>Seleção premium para quem não abre mão de segurança, desempenho e procedência.</p><div className="hero-cta"><a className="primary" href="#ofertas">Ver ofertas <ChevronRight/></a><a className="secondary" href="#compatibilidade">Buscar por veículo</a></div><div className="proof"><div><b>12x</b><span>sem juros</span></div><div><b>24h</b><span>para despachar</span></div><div><b>90 dias</b><span>de garantia</span></div></div></div><div className="hero-art"><div className="disc"/><div className="caliper">HP<span>RACING</span></div><div className="float"><ShieldCheck/><span>Compatibilidade<br/><b>verificada</b></span></div></div></section>
    <VehicleFinder/>
    <section className="section" id="categorias"><Title kicker="ESCOLHA SUA CATEGORIA" title="Tudo para o seu projeto."/><div className="category-grid">{categories.slice(1).map((c,i)=><button key={c} onClick={()=>{setCategory(c);document.querySelector("#ofertas")?.scrollIntoView({behavior:"smooth"})}}><i>{["◉","⌁","⚙","ϟ","◎","✦"][i]}</i><b>{c}</b><small>{12+i*7} produtos</small><ChevronRight/></button>)}</div></section>
    <section className="section products" id="ofertas"><div className="section-head"><Title kicker="CATÁLOGO HIGHPARTS" title="Peças do estoque real."/><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar peça ou veículo"/><SlidersHorizontal/></div></div><div className="chips">{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=>{const available=p.price!=null&&p.stock!=null&&p.stock>0;return <article className="product" key={p.id}>{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart"><Heart/></button><PartVisual product={p}/><div className="product-body"><small>{p.category} • {p.id}</small><h3>{p.name}</h3><p>{p.fit}</p><div className="price">{available?<><b>{money(p.price!)}</b><span>ou 12x de {money(p.price!/12)} • {p.stock} em estoque</span></>:<><b>Consulte disponibilidade</b><span>Preço e estoque serão publicados pelo administrador</span></>}</div><button className="buy" disabled={!available} onClick={()=>{if(available){setCart([...cart,p.id]);setCartOpen(true)}}}><ShoppingCart/> {available?"Adicionar ao carrinho":"Indisponível"}</button></div></article>})}</div>{(catalogLoading||!filtered.length)&&<p className="empty">{catalogLoading?"Carregando catálogo...":"Nenhuma peça encontrada."}</p>}</section>
    <section className="benefits"><Benefit icon={<Truck/>} title="Envio rápido" text="Despacho em até 24h úteis"/><Benefit icon={<ShieldCheck/>} title="Compra protegida" text="Ambiente seguro e criptografado"/><Benefit icon={<PackageCheck/>} title="Peças selecionadas" text="Qualidade e procedência"/><Benefit icon={<Star/>} title="Suporte especialista" text="Ajuda para escolher a peça certa"/></section>
    <footer id="suporte"><img src="/highparts-logo.png" alt="HighParts"/><p>Performance, confiança e a peça certa para o seu carro.</p><div><a href="/trocas-e-devolucoes">Trocas e devoluções</a><a href="/privacidade">Política de privacidade</a><a href="/termos">Termos de uso</a><a href="mailto:alisson@highparts.com.br">Fale conosco</a></div><small>© 2026 HighParts. Catálogo sujeito à disponibilidade de estoque.</small></footer>
    <div className={`overlay ${cartOpen?"show":""}`} onClick={()=>setCartOpen(false)}/><aside className={`drawer ${cartOpen?"show":""}`}><header><div><small>SEU CARRINHO</small><h2>{cart.length} {cart.length===1?"item":"itens"}</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></header>{!items.length?<div className="cart-empty"><ShoppingCart/><h3>Seu carrinho está vazio</h3><p>Adicione peças e elas aparecerão aqui.</p><button onClick={()=>setCartOpen(false)}>Explorar produtos</button></div>:<><div className="cart-items">{items.map((p,i)=><div className="cart-item" key={`${p.id}-${i}`}><PartVisual product={p}/><span><b>{p.name}</b><small>{p.fit}</small><strong>{money(p.price??0)}</strong></span><button onClick={()=>setCart(cart.filter((_,n)=>n!==i))}><X/></button></div>)}</div><div className="cart-total"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><small>Frete calculado no checkout</small><button onClick={()=>{setCartOpen(false);setCheckout(true)}}>Ir para o checkout <ChevronRight/></button><em><ShieldCheck/> Compra segura</em></div></>}</aside>
  </main>
}

function Title({kicker,title}:{kicker:string;title:string}){return <div className="title"><small>{kicker}</small><h2>{title}</h2></div>}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div>{icon}<span><b>{title}</b><small>{text}</small></span></div>}

function Checkout({items,subtotal,onBack}:{items:Product[];subtotal:number;onBack:()=>void}){
 const [orderId,setOrderId]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 async function finish(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const fields=Object.fromEntries(new FormData(event.currentTarget));const grouped=[...new Set(items.map(p=>p.id))].map(id=>({itemKey:id,quantity:items.filter(x=>x.id===id).length}));const response=await fetch("/api/account/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone:fields.phone,postalCode:fields.postalCode,address:`${fields.address}, ${fields.number} ${fields.complement??""} - ${fields.state}`,items:grouped})});const result=await response.json() as {error?:string;order?:{id:string}};if(response.status===401){location.href="/entrar?returnTo=/";return}if(!response.ok||!result.order){setError(result.error??"Não foi possível criar o pedido.");setSaving(false);return}setOrderId(result.order.id)}
 if(orderId)return <main className="checkout"><div className="success"><i><Check/></i><small>PEDIDO RECEBIDO</small><h1>Pedido salvo!</h1><p>Pedido <b>#{orderId}</b> criado. Ele ficará aguardando pagamento até conectarmos o provedor.</p><a href="/conta">Acompanhar em minha conta</a><button onClick={onBack}>Voltar para a loja</button></div></main>;
 return <main className="checkout"><header><img src="/highparts-logo.png" alt="HighParts"/><button onClick={onBack}>← Continuar comprando</button><span><ShieldCheck/> Checkout seguro</span></header><div className="checkout-grid"><form onSubmit={finish}><small>FINALIZAR COMPRA</small><h1>Quase lá.</h1><FormCard number="1" title="Contato" subtitle="Usaremos os dados da sua conta"><div className="form-grid"><label>Telefone<input name="phone" placeholder="(00) 00000-0000" required/></label></div></FormCard><FormCard number="2" title="Entrega" subtitle="Informe o endereço de destino"><div className="form-grid"><label>CEP<input name="postalCode" placeholder="00000-000" required/></label><label>Estado<select name="state" required><option value="">Selecione</option><option>SP</option><option>PR</option><option>SC</option><option>RS</option><option>MG</option><option>RJ</option></select></label><label className="full">Endereço<input name="address" placeholder="Rua, avenida..." required/></label><label>Número<input name="number" placeholder="123" required/></label><label>Complemento<input name="complement" placeholder="Opcional"/></label></div></FormCard><FormCard number="3" title="Pagamento" subtitle="Será ativado após configurar o provedor"><div className="payment-tabs"><button type="button" className="active">Pix</button><button type="button">Cartão</button><button type="button">Boleto</button></div><p style={{fontSize:10,color:"#777"}}>Nenhum dado de cartão é solicitado enquanto a integração de pagamento não estiver configurada.</p></FormCard>{error&&<p className="checkout-error">{error}</p>}<button className="finish" disabled={!items.length||saving}>{saving?"Salvando pedido...":`Criar pedido • ${money(subtotal)}`} <ChevronRight/></button></form><aside className="order"><small>RESUMO DO PEDIDO</small>{items.map((p,i)=><div className="order-item" key={i}><PartVisual product={p}/><span><b>{p.name}</b><small>Qtd. 1</small></span><strong>{money(p.price??0)}</strong></div>)}<div className="totals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Frete</span><b>{subtotal>=499?"Grátis":"A calcular"}</b></p><p><span>Total</span><strong>{money(subtotal)}</strong></p></div><div className="secure"><ShieldCheck/><span><b>Pedido protegido</b><small>Seus dados ficam vinculados à sua conta</small></span></div></aside></div></main>
}
function FormCard({number,title,subtitle,children}:{number:string;title:string;subtitle:string;children:React.ReactNode}){return <div className="form-card"><div className="step"><b>{number}</b><span><strong>{title}</strong><small>{subtitle}</small></span></div>{children}</div>}
