"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BarChart3, Box, Check, ChevronRight, CircleUserRound, Gauge, Heart, Menu, PackageCheck, Search, ShieldCheck, ShoppingCart, SlidersHorizontal, Star, Truck, X, Zap } from "lucide-react";
import VehicleFinder from "./vehicle-finder";

type Product = { id:number; name:string; category:string; fit:string; price:number; old?:number; badge?:string; tone:string };
const products:Product[] = [
  {id:1,name:"Kit Disco + Pastilha Performance",category:"Freios",fit:"Golf • Jetta • Audi A3",price:849.9,old:999.9,badge:"Mais vendido",tone:"#e31b2d"},
  {id:2,name:"Amortecedor Pressurizado Pro",category:"Suspensão",fit:"Onix • Prisma • Cobalt",price:389.9,badge:"Pronta entrega",tone:"#f5b800"},
  {id:3,name:"Filtro de Ar Inbox HP",category:"Motor",fit:"Civic • HR-V • City",price:189.9,old:219.9,badge:"Oferta",tone:"#ff6b35"},
  {id:4,name:"Farol LED Ultra Vision H7",category:"Elétrica",fit:"Encaixe universal H7",price:279.9,badge:"Lançamento",tone:"#4dabf7"},
  {id:5,name:"Embreagem Reforçada Stage 1",category:"Transmissão",fit:"Gol • Saveiro • Voyage",price:1299.9,tone:"#8b5cf6"},
  {id:6,name:"Óleo Sintético 5W30 — Kit 4L",category:"Manutenção",fit:"Padrão API SP / ILSAC GF-6",price:219.9,old:249.9,badge:"-12%",tone:"#22c55e"},
];
const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

function PartVisual({product}:{product:Product}) { return <div className="part" style={{"--tone":product.tone} as React.CSSProperties}><i/><b>{product.category}</b></div> }

export default function Home(){
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("Todos"); const [cart,setCart]=useState<number[]>([]); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false); const [menu,setMenu]=useState(false); const [user,setUser]=useState<{name:string}|null>(null); const [cartReady,setCartReady]=useState(false);
  useEffect(()=>{(async()=>{const local=JSON.parse(localStorage.getItem("highparts_cart")||"[]") as number[];const me=await fetch("/api/auth/me").then(r=>r.json()).catch(()=>({user:null}));setUser(me.user);if(me.user){const saved=await fetch("/api/account/cart").then(r=>r.json()).catch(()=>({items:[]}));const remote=(saved.items||[]).flatMap((item:any)=>Array.from({length:item.quantity},()=>Number(item.itemKey))).filter((id:number)=>products.some(p=>p.id===id));setCart(remote.length?remote:local)}else setCart(local);setCartReady(true)})()},[]);
  useEffect(()=>{if(!cartReady)return;localStorage.setItem("highparts_cart",JSON.stringify(cart));if(user){const grouped=[...new Set(cart)].map(id=>{const p=products.find(product=>product.id===id)!;return {itemKey:String(id),name:p.name,fit:p.fit,priceCents:Math.round(p.price*100),quantity:cart.filter(item=>item===id).length}});fetch("/api/account/cart",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({items:grouped})})}},[cart,cartReady,user]);
  const categories=["Todos","Freios","Suspensão","Motor","Elétrica","Transmissão","Manutenção"];
  const filtered=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&`${p.name} ${p.fit}`.toLowerCase().includes(query.toLowerCase())),[query,category]);
  const items=cart.map(id=>products.find(p=>p.id===id)!).filter(Boolean); const subtotal=items.reduce((s,p)=>s+p.price,0);
  if(checkout) return <Checkout items={items} subtotal={subtotal} onBack={()=>setCheckout(false)}/>;
  return <main>
    <div className="topbar"><span>Frete grátis acima de R$ 499 para Sul e Sudeste</span><span>Compra 100% segura</span></div>
    <header className="header"><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button><a href="#inicio"><img className="logo" src="/highparts-logo.png" alt="HighParts"/></a><nav className={menu?"open":""}><a href="#categorias">Categorias</a><a href="#ofertas">Ofertas</a><a href="#compatibilidade">Encontre sua peça</a><a href="#suporte">Suporte</a></nav><div className="header-actions"><a className="admin-link" href={user?"/conta":"/entrar"}><CircleUserRound/> {user?user.name.split(" ")[0]:"Entrar"}</a><button className="cart-icon" onClick={()=>setCartOpen(true)}><ShoppingCart/><b>{cart.length}</b></button></div></header>
    <section className="hero" id="inicio"><div className="hero-copy"><div className="eyebrow"><Zap/> PERFORMANCE COMEÇA NA ESCOLHA CERTA</div><h1>PEÇAS QUE LEVAM<br/>SEU CARRO <em>ALÉM.</em></h1><p>Seleção premium para quem não abre mão de segurança, desempenho e procedência.</p><div className="hero-cta"><a className="primary" href="#ofertas">Ver ofertas <ChevronRight/></a><a className="secondary" href="#compatibilidade">Buscar por veículo</a></div><div className="proof"><div><b>12x</b><span>sem juros</span></div><div><b>24h</b><span>para despachar</span></div><div><b>90 dias</b><span>de garantia</span></div></div></div><div className="hero-art"><div className="disc"/><div className="caliper">HP<span>RACING</span></div><div className="float"><ShieldCheck/><span>Compatibilidade<br/><b>verificada</b></span></div></div></section>
    <VehicleFinder/>
    <section className="section" id="categorias"><Title kicker="ESCOLHA SUA CATEGORIA" title="Tudo para o seu projeto."/><div className="category-grid">{categories.slice(1).map((c,i)=><button key={c} onClick={()=>{setCategory(c);document.querySelector("#ofertas")?.scrollIntoView({behavior:"smooth"})}}><i>{["◉","⌁","⚙","ϟ","◎","✦"][i]}</i><b>{c}</b><small>{12+i*7} produtos</small><ChevronRight/></button>)}</div></section>
    <section className="section products" id="ofertas"><div className="section-head"><Title kicker="DESTAQUES HIGHPARTS" title="Feitos para performar."/><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar peça ou veículo"/><SlidersHorizontal/></div></div><div className="chips">{categories.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=><article className="product" key={p.id}>{p.badge&&<span className="badge">{p.badge}</span>}<button className="heart"><Heart/></button><PartVisual product={p}/><div className="product-body"><small>{p.category}</small><h3>{p.name}</h3><p>{p.fit}</p><div className="rating">★★★★★ <span>(28)</span></div><div className="price">{p.old&&<del>{money(p.old)}</del>}<b>{money(p.price)}</b><span>ou 12x de {money(p.price/12)}</span></div><button className="buy" onClick={()=>{setCart([...cart,p.id]);setCartOpen(true)}}><ShoppingCart/> Adicionar ao carrinho</button></div></article>)}</div>{!filtered.length&&<p className="empty">Nenhuma peça encontrada.</p>}</section>
    <section className="benefits"><Benefit icon={<Truck/>} title="Envio rápido" text="Despacho em até 24h úteis"/><Benefit icon={<ShieldCheck/>} title="Compra protegida" text="Ambiente seguro e criptografado"/><Benefit icon={<PackageCheck/>} title="Peças selecionadas" text="Qualidade e procedência"/><Benefit icon={<Star/>} title="Suporte especialista" text="Ajuda para escolher a peça certa"/></section>
    <footer id="suporte"><img src="/highparts-logo.png" alt="HighParts"/><p>Performance, confiança e a peça certa para o seu carro.</p><div><a href="/trocas-e-devolucoes">Trocas e devoluções</a><a href="/privacidade">Política de privacidade</a><a href="/termos">Termos de uso</a><a href="mailto:alisson@highparts.com.br">Fale conosco</a></div><small>© 2026 HighParts. Catálogo e preços demonstrativos.</small></footer>
    <div className={`overlay ${cartOpen?"show":""}`} onClick={()=>setCartOpen(false)}/><aside className={`drawer ${cartOpen?"show":""}`}><header><div><small>SEU CARRINHO</small><h2>{cart.length} {cart.length===1?"item":"itens"}</h2></div><button onClick={()=>setCartOpen(false)}><X/></button></header>{!items.length?<div className="cart-empty"><ShoppingCart/><h3>Seu carrinho está vazio</h3><p>Adicione peças e elas aparecerão aqui.</p><button onClick={()=>setCartOpen(false)}>Explorar produtos</button></div>:<><div className="cart-items">{items.map((p,i)=><div className="cart-item" key={`${p.id}-${i}`}><PartVisual product={p}/><span><b>{p.name}</b><small>{p.fit}</small><strong>{money(p.price)}</strong></span><button onClick={()=>setCart(cart.filter((_,n)=>n!==i))}><X/></button></div>)}</div><div className="cart-total"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><small>Frete calculado no checkout</small><button onClick={()=>{setCartOpen(false);setCheckout(true)}}>Ir para o checkout <ChevronRight/></button><em><ShieldCheck/> Compra segura</em></div></>}</aside>
  </main>
}

function Title({kicker,title}:{kicker:string;title:string}){return <div className="title"><small>{kicker}</small><h2>{title}</h2></div>}
function Benefit({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div>{icon}<span><b>{title}</b><small>{text}</small></span></div>}

function Checkout({items,subtotal,onBack}:{items:Product[];subtotal:number;onBack:()=>void}){
 const [orderId,setOrderId]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
 async function finish(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const fields=Object.fromEntries(new FormData(event.currentTarget));const grouped=[...new Set(items.map(p=>p.id))].map(id=>{const p=products.find(x=>x.id===id)!;return {itemKey:String(id),name:p.name,priceCents:Math.round(p.price*100),quantity:items.filter(x=>x.id===id).length}});const response=await fetch("/api/account/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone:fields.phone,postalCode:fields.postalCode,address:`${fields.address}, ${fields.number} ${fields.complement??""} - ${fields.state}`,items:grouped})});const result=await response.json();if(response.status===401){location.href="/entrar?returnTo=/";return}if(!response.ok){setError(result.error??"Não foi possível criar o pedido.");setSaving(false);return}setOrderId(result.order.id)}
 if(orderId)return <main className="checkout"><div className="success"><i><Check/></i><small>PEDIDO RECEBIDO</small><h1>Pedido salvo!</h1><p>Pedido <b>#{orderId}</b> criado. Ele ficará aguardando pagamento até conectarmos o provedor.</p><a href="/conta">Acompanhar em minha conta</a><button onClick={onBack}>Voltar para a loja</button></div></main>;
 return <main className="checkout"><header><img src="/highparts-logo.png" alt="HighParts"/><button onClick={onBack}>← Continuar comprando</button><span><ShieldCheck/> Checkout seguro</span></header><div className="checkout-grid"><form onSubmit={finish}><small>FINALIZAR COMPRA</small><h1>Quase lá.</h1><FormCard number="1" title="Contato" subtitle="Usaremos os dados da sua conta"><div className="form-grid"><label>Telefone<input name="phone" placeholder="(00) 00000-0000" required/></label></div></FormCard><FormCard number="2" title="Entrega" subtitle="Informe o endereço de destino"><div className="form-grid"><label>CEP<input name="postalCode" placeholder="00000-000" required/></label><label>Estado<select name="state" required><option value="">Selecione</option><option>SP</option><option>PR</option><option>SC</option><option>RS</option><option>MG</option><option>RJ</option></select></label><label className="full">Endereço<input name="address" placeholder="Rua, avenida..." required/></label><label>Número<input name="number" placeholder="123" required/></label><label>Complemento<input name="complement" placeholder="Opcional"/></label></div></FormCard><FormCard number="3" title="Pagamento" subtitle="Será ativado após configurar o provedor"><div className="payment-tabs"><button type="button" className="active">Pix</button><button type="button">Cartão</button><button type="button">Boleto</button></div><p style={{fontSize:10,color:"#777"}}>Nenhum dado de cartão é solicitado enquanto a integração de pagamento não estiver configurada.</p></FormCard>{error&&<p className="checkout-error">{error}</p>}<button className="finish" disabled={!items.length||saving}>{saving?"Salvando pedido...":`Criar pedido • ${money(subtotal)}`} <ChevronRight/></button></form><aside className="order"><small>RESUMO DO PEDIDO</small>{items.map((p,i)=><div className="order-item" key={i}><PartVisual product={p}/><span><b>{p.name}</b><small>Qtd. 1</small></span><strong>{money(p.price)}</strong></div>)}<div className="totals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Frete</span><b>{subtotal>=499?"Grátis":"A calcular"}</b></p><p><span>Total</span><strong>{money(subtotal)}</strong></p></div><div className="secure"><ShieldCheck/><span><b>Pedido protegido</b><small>Seus dados ficam vinculados à sua conta</small></span></div></aside></div></main>
}
function FormCard({number,title,subtitle,children}:{number:string;title:string;subtitle:string;children:React.ReactNode}){return <div className="form-card"><div className="step"><b>{number}</b><span><strong>{title}</strong><small>{subtitle}</small></span></div>{children}</div>}

function Admin({onBack}:{onBack:()=>void}){const orders=[{id:"#HP-2840",name:"Marcos Silva",value:"R$ 849,90",status:"Pago",date:"Hoje, 14:32"},{id:"#HP-2839",name:"Ana Costa",value:"R$ 1.299,90",status:"Separando",date:"Hoje, 11:18"},{id:"#HP-2838",name:"João Lima",value:"R$ 409,80",status:"Enviado",date:"Ontem, 17:45"},{id:"#HP-2837",name:"Carla Souza",value:"R$ 279,90",status:"Pago",date:"Ontem, 15:09"}];return <main className="admin"><aside><img src="/highparts-logo.png" alt="HighParts"/><small>PAINEL ADMIN</small><nav><button className="active"><Gauge/> Visão geral</button><button><ShoppingCart/> Pedidos <b>8</b></button><button><Box/> Produtos</button><button><BarChart3/> Relatórios</button></nav><button className="back" onClick={onBack}>← Voltar para a loja</button></aside><section><header><div><small>QUARTA-FEIRA, 07 DE OUTUBRO</small><h1>Bom dia, Admin.</h1></div><i>AD</i></header><div className="metrics"><Metric name="FATURAMENTO HOJE" value="R$ 4.839,20" note="↑ 12,4% vs. ontem"/><Metric name="PEDIDOS" value="18" note="8 aguardando envio"/><Metric name="TICKET MÉDIO" value="R$ 268,84" note="↑ 4,2% este mês"/><Metric name="ESTOQUE BAIXO" value="6" note="Requer atenção"/></div><div className="admin-grid"><article className="chart-card"><div><span><small>VENDAS NOS ÚLTIMOS 7 DIAS</small><h2>R$ 28.420,60</h2></span><select><option>7 dias</option></select></div><div className="chart">{[42,66,53,82,72,94,68].map((h,i)=><span key={i} style={{height:`${h}%`}}><i>{["Qui","Sex","Sáb","Dom","Seg","Ter","Qua"][i]}</i></span>)}</div></article><article className="stock"><small>ALERTAS DE ESTOQUE</small><h2>Reposição necessária</h2>{products.slice(1,4).map((p,i)=><div key={p.id}><i style={{background:p.tone}}/><span><b>{p.name}</b><small>{[3,5,7][i]} unidades restantes</small></span><ChevronRight/></div>)}</article></div><article className="orders"><div><span><small>PEDIDOS RECENTES</small><h2>Acompanhe suas vendas</h2></span><button>Ver todos <ChevronRight/></button></div><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Valor</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td>{o.name}</td><td>{o.date}</td><td><b>{o.value}</b></td><td><span className={`status ${o.status.toLowerCase()}`}>{o.status}</span></td></tr>)}</tbody></table></article><p className="demo-note">Painel demonstrativo. Em produção, o acesso será restrito ao administrador autenticado e os dados virão do banco de vendas.</p></section></main>}
function Metric({name,value,note}:{name:string;value:string;note:string}){return <article><small>{name}</small><strong>{value}</strong><span>{note}</span></article>}
