"use client";

import { Check, ChevronLeft, ChevronRight, Disc3, Gauge, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type CatalogItem = { code:string; application:string; axle:string; product:string; type:string; hub:string; original:string };
type Vehicle = { brand:string; model:string; version:string; year:string };
type Stage = "plate"|"item"|"details"|"results";

const productChoices = [
  {label:"Disco de freio",match:"DISCO DE FREIO",icon:"◉"},
  {label:"Tambor de freio",match:"TAMBOR DE FREIO",icon:"◎"},
  {label:"Cubo de roda",match:"CUBO DE RODA",icon:"⌾"},
  {label:"Cilindro mestre",match:"CILINDRO MESTRE",icon:"▣"},
];

export default function VehicleFinder(){
  const [open,setOpen]=useState(false); const [stage,setStage]=useState<Stage>("plate"); const [plate,setPlate]=useState(""); const [vehicle,setVehicle]=useState<Vehicle|null>(null); const [catalog,setCatalog]=useState<CatalogItem[]>([]); const [product,setProduct]=useState(""); const [abs,setAbs]=useState("Não sei"); const [axle,setAxle]=useState("DIANT."); const [engine,setEngine]=useState("1.6"); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{fetch("/catalog.json").then(r=>r.json()).then(setCatalog).catch(()=>setCatalog([]))},[]);
  const normalized=plate.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7);
  const lookup=()=>{if(normalized.length!==7){setError("Digite uma placa válida com 7 caracteres.");return}setError("");setLoading(true);setTimeout(()=>{setVehicle(normalized==="ABC1234"?{brand:"Volkswagen",model:"Gol",version:"1.6",year:"2001"}:{brand:"Volkswagen",model:"Gol",version:"1.6",year:"2001"});setLoading(false);setStage("item")},650)};
  const results=useMemo(()=>catalog.filter(i=>{const app=i.application.toUpperCase();const prod=i.product.toUpperCase();const axleOk=axle==="QUALQUER"||i.axle.toUpperCase().includes(axle);const absOk=abs==="Não sei"||(abs==="Sim"?!app.includes("- ABS")&&!app.includes("(- ABS"):!app.includes("+ ABS"));return app.includes("[VW]")&&app.includes("GOL")&&app.includes(engine)&&prod.includes(product)&&axleOk&&absOk}).slice(0,12),[catalog,product,abs,axle,engine]);
  const reset=()=>{setStage("plate");setVehicle(null);setProduct("");setError("")};
  return <>
    <section className="finder plate-finder" id="compatibilidade"><div><strong>01</strong><span><b>ENCONTRE PELA PLACA</b><small>Identifique o carro e refine a peça</small></span></div><div className="plate-input"><span>BR</span><input value={normalized} onChange={e=>setPlate(e.target.value)} onKeyDown={e=>e.key==="Enter"&&lookup()} placeholder="ABC1D23" aria-label="Placa do veículo"/></div><div className="finder-copy"><ShieldCheck/><span>Aplicação conferida<br/><b>com o catálogo HighParts</b></span></div><button onClick={()=>setOpen(true)}><Search/> Consultar placa</button></section>
    <div className={`vehicle-overlay ${open?"show":""}`} onClick={()=>setOpen(false)}/>
    <section className={`vehicle-modal ${open?"show":""}`} aria-hidden={!open}><header><img src="/highparts-logo.png" alt="HighParts"/><span>ASSISTENTE DE COMPATIBILIDADE</span><button onClick={()=>setOpen(false)} aria-label="Fechar"><X/></button></header><div className="vehicle-progress"><i className="active"/><i className={stage!=="plate"?"active":""}/><i className={stage==="details"||stage==="results"?"active":""}/><i className={stage==="results"?"active":""}/></div>
      {stage==="plate"&&<div className="vehicle-step intro"><small>PASSO 1 DE 4</small><h2>Qual é a placa do carro?</h2><p>Usaremos a placa para identificar o veículo e fazer as perguntas certas.</p><label className="big-plate"><span>BRASIL</span><input autoFocus value={normalized} onChange={e=>setPlate(e.target.value)} onKeyDown={e=>e.key==="Enter"&&lookup()} placeholder="ABC1D23"/></label>{error&&<em>{error}</em>}<button className="vehicle-next" onClick={lookup} disabled={loading}>{loading?"Identificando veículo...":"Identificar veículo"}<ChevronRight/></button><div className="demo-hint"><Sparkles/><span><b>Teste agora com ABC1234</b><small>A consulta está em modo demonstrativo até conectarmos a API de placas.</small></span></div></div>}
      {stage==="item"&&vehicle&&<div className="vehicle-step"><small>PASSO 2 DE 4</small><div className="identified"><Check/><span><b>{vehicle.brand} {vehicle.model}</b><small>{vehicle.version} • {vehicle.year} • Placa {normalized}</small></span><button onClick={reset}>Alterar</button></div><h2>Qual peça você procura?</h2><p>Escolha uma categoria para buscarmos no catálogo Hipper Freios.</p><div className="choice-grid">{productChoices.map(c=><button key={c.match} onClick={()=>{setProduct(c.match);setStage("details")}}><i>{c.icon}</i><b>{c.label}</b><ChevronRight/></button>)}</div></div>}
      {stage==="details"&&<div className="vehicle-step"><small>PASSO 3 DE 4</small><button className="step-back" onClick={()=>setStage("item")}><ChevronLeft/> Voltar</button><h2>Só mais alguns detalhes.</h2><p>Essas respostas eliminam peças parecidas que não servem no seu carro.</p><Question title="O veículo possui ABS?" value={abs} options={["Sim","Não","Não sei"]} onChange={setAbs}/><Question title="Em qual eixo vai a peça?" value={axle} options={["DIANT.","TRAS.","QUALQUER"]} labels={["Dianteiro","Traseiro","Não sei"]} onChange={setAxle}/><Question title="Qual é a motorização?" value={engine} options={["1.0","1.6","1.8","2.0"]} onChange={setEngine}/><button className="vehicle-next" onClick={()=>setStage("results")}>Ver peças compatíveis <ChevronRight/></button></div>}
      {stage==="results"&&<div className="vehicle-step results"><small>PASSO 4 DE 4</small><div className="result-head"><span><h2>{results.length} peças encontradas</h2><p>{vehicle?.brand} {vehicle?.model} {engine} • {abs==="Não sei"?"ABS não informado":`${abs==="Sim"?"Com":"Sem"} ABS`} • {axle==="DIANT."?"Dianteiro":axle==="TRAS."?"Traseiro":"Todos os eixos"}</p></span><button onClick={()=>setStage("details")}>Ajustar respostas</button></div><div className="catalog-results">{results.map(item=><article key={item.code}><div className="mini-disc"><Disc3/></div><div><small>{item.product} • {item.axle}</small><h3>{item.code}</h3><p>{item.type||"Aplicação original"}{item.hub?` • Cubo ${item.hub.toLowerCase()}`:""}</p><details><summary>Ver aplicação completa</summary><p>{item.application}</p></details></div><button onClick={()=>{window.dispatchEvent(new CustomEvent("highparts:search",{detail:item.code}));setOpen(false)}}>Ver produto <ChevronRight/></button></article>)}{!results.length&&<div className="no-result"><Gauge/><h3>Nenhum item com todos esses filtros</h3><p>Tente marcar “Não sei” em ABS ou eixo para ampliar a busca.</p><button onClick={()=>setStage("details")}>Revisar respostas</button></div>}</div><div className="catalog-note"><ShieldCheck/><span><b>Dados do catálogo Hipper Freios</b><small>{catalog.length.toLocaleString("pt-BR")} aplicações importadas. Confirme ano e versão antes da compra.</small></span></div></div>}
    </section>
  </>
}

function Question({title,value,options,labels,onChange}:{title:string;value:string;options:string[];labels?:string[];onChange:(v:string)=>void}){return <fieldset className="vehicle-question"><legend>{title}</legend><div>{options.map((o,i)=><button type="button" className={value===o?"active":""} onClick={()=>onChange(o)} key={o}>{value===o&&<Check/>}{labels?.[i]||o}</button>)}</div></fieldset>}
