"use client";

import { FormEvent,useEffect,useState } from "react";
import { Car,CheckCircle2,LoaderCircle,LogOut,MailWarning,MapPin,Package,Plus,ShoppingCart,Trash2 } from "lucide-react";

type User={id:string;name:string;email:string;role:string;phone:string;emailVerifiedAt:string|null};
type Vehicle={id:string;plate:string;brand:string;model:string;year:string;version:string;hasAbs:number|null;nickname:string};
type Order={id:string;totalCents:number;status:string;paymentProvider:string;vehiclePlate:string;shippingAddress:string;createdAt:string;itemCount:number};
type Address={id:string;label:string;postalCode:string;street:string;number:string;complement:string;neighborhood:string;city:string;state:string;isDefault:number};
const money=(c:number)=>(c/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusLabel:Record<string,string>={awaiting_payment:"Aguardando pagamento",paid:"Pagamento aprovado",processing:"Em separação",shipped:"Enviado",delivered:"Entregue",cancelled:"Cancelado"};

export default function AccountDashboard({user}:{user:User}){
  const [vehicles,setVehicles]=useState<Vehicle[]>([]);
  const [orders,setOrders]=useState<Order[]>([]);
  const [addresses,setAddresses]=useState<Address[]>([]);
  const [showVehicle,setShowVehicle]=useState(false);
  const [message,setMessage]=useState("");
  const [sending,setSending]=useState(false);
  const [showAddress,setShowAddress]=useState(false);
  const [lookingUpCep,setLookingUpCep]=useState(false);
  const [addressDraft,setAddressDraft]=useState({postalCode:"",street:"",neighborhood:"",city:"",state:""});
  const load=async()=>{const [v,o,a]=await Promise.all([fetch("/api/account/vehicles").then(r=>r.json()),fetch("/api/account/orders").then(r=>r.json()),fetch("/api/account/addresses").then(r=>r.json())]);setVehicles(v.vehicles??[]);setOrders(o.orders??[]);setAddresses(a.addresses??[])};
  useEffect(()=>{load()},[]);
  async function resend(){setSending(true);const r=await fetch("/api/auth/resend-verification",{method:"POST"});const d=await r.json();setMessage(r.ok?"E-mail de confirmação enviado. Verifique também a caixa de spam.":d.error);setSending(false)}
  async function addVehicle(e:FormEvent<HTMLFormElement>){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/account/vehicles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(r.ok?"Veículo salvo na sua garagem.":d.error);if(r.ok){e.currentTarget.reset();setShowVehicle(false);load()}}
  async function removeVehicle(id:string){await fetch(`/api/account/vehicles/${id}`,{method:"DELETE"});load()}
  async function lookupCep(value:string){const cep=value.replace(/\D/g,"").slice(0,8);setAddressDraft(d=>({...d,postalCode:cep}));if(cep.length!==8)return;setLookingUpCep(true);try{const data=await fetch(`https://viacep.com.br/ws/${cep}/json/`).then(r=>r.json()) as {erro?:boolean;logradouro?:string;bairro?:string;localidade?:string;uf?:string};if(data.erro)throw new Error();setAddressDraft({postalCode:cep,street:data.logradouro||"",neighborhood:data.bairro||"",city:data.localidade||"",state:data.uf||""})}catch{setMessage("CEP não encontrado. Preencha o endereço manualmente.")}finally{setLookingUpCep(false)}}
  async function addAddress(e:FormEvent<HTMLFormElement>){e.preventDefault();const body={...Object.fromEntries(new FormData(e.currentTarget)),...addressDraft};const r=await fetch("/api/account/addresses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(r.ok?"Endereço salvo.":d.error);if(r.ok){e.currentTarget.reset();setAddressDraft({postalCode:"",street:"",neighborhood:"",city:"",state:""});setShowAddress(false);load()}}
  async function removeAddress(id:string){await fetch(`/api/account/addresses/${id}`,{method:"DELETE"});load()}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/"}
  return <main className="account"><aside><img src="/highparts-logo.png" alt="HighParts"/><nav><a href="#vehicles"><Car/> Meus veículos</a><a href="#addresses"><MapPin/> Endereços</a><a href="#orders"><Package/> Pedidos</a><a href="/"><ShoppingCart/> Continuar comprando</a>{user.role==="admin"&&<><a href="/admin">Painel administrativo</a><a href="/admin/seguranca">Segurança e acessos</a></>}</nav><button onClick={logout}><LogOut/> Sair</button></aside><section>
    <header><small>MINHA CONTA</small><h1>Olá, {user.name.split(" ")[0]}.</h1><p>{user.email}</p></header>
    {!user.emailVerifiedAt&&<div className="verification-alert"><MailWarning/><span><b>Confirme seu e-mail</b><small>A confirmação será exigida antes de finalizar uma compra.</small></span><button onClick={resend} disabled={sending}>{sending?"Enviando...":"Reenviar confirmação"}</button></div>}
    {message&&<div className="account-message">{message}</div>}
    <div className="account-overview"><span><Car/><b>{vehicles.length}</b><small>{vehicles.length===1?"veículo salvo":"veículos salvos"}</small></span><span><MapPin/><b>{addresses.length}</b><small>{addresses.length===1?"endereço salvo":"endereços salvos"}</small></span><span><Package/><b>{orders.length}</b><small>{orders.length===1?"pedido realizado":"pedidos realizados"}</small></span></div>
    <article id="vehicles" className="account-card"><div className="account-card-head"><span><small>GARAGEM</small><h2>Meus veículos</h2></span><button onClick={()=>setShowVehicle(!showVehicle)}><Plus/> Adicionar veículo</button></div>{showVehicle&&<form className="vehicle-form expanded" onSubmit={addVehicle}><label>Placa<input name="plate" placeholder="ABC1D23" required maxLength={7}/></label><label>Apelido<input name="nickname" placeholder="Ex.: Meu Gol"/></label><label>Marca<input name="brand" placeholder="Ex.: Volkswagen" required/></label><label>Modelo<input name="model" placeholder="Ex.: Gol" required/></label><label>Ano<input name="year" inputMode="numeric" maxLength={4} placeholder="Ex.: 2018"/></label><label>Versão / motor<input name="version" placeholder="Ex.: 1.6 MSI"/></label><label>Possui ABS?<select name="hasAbs" defaultValue=""><option value="">Não sei</option><option value="true">Sim</option><option value="false">Não</option></select></label><button>Salvar veículo</button></form>}<div className="vehicle-list">{vehicles.length?vehicles.map(v=><div key={v.id}><Car/><span><b>{v.nickname||`${v.brand} ${v.model}`||"Meu veículo"}</b><small>{v.plate}{v.year&&` • ${v.year}`}{v.version&&` • ${v.version}`}{v.hasAbs!=null&&` • ${v.hasAbs?"Com ABS":"Sem ABS"}`}</small></span><a href={`/?vehicle=${encodeURIComponent(v.plate)}#compatibilidade`}>Buscar peças</a><button onClick={()=>removeVehicle(v.id)} aria-label={`Remover ${v.plate}`}><Trash2/></button></div>):<div className="account-empty-state"><Car/><b>Sua garagem está vazia</b><p>Salve um veículo para consultar peças com mais rapidez.</p></div>}</div></article>
    <article id="addresses" className="account-card"><div className="account-card-head"><span><small>ENTREGA</small><h2>Meus endereços</h2></span><button onClick={()=>setShowAddress(!showAddress)}><Plus/> Adicionar endereço</button></div>{showAddress&&<form className="address-form" onSubmit={addAddress}><label>Nome do endereço<input name="label" placeholder="Casa, trabalho..." defaultValue="Casa"/></label><label>CEP<span className="cep-field"><input name="postalCode" inputMode="numeric" placeholder="00000-000" value={addressDraft.postalCode} onChange={e=>lookupCep(e.target.value)}/>{lookingUpCep&&<LoaderCircle className="spin"/>}</span></label><label className="wide">Rua<input name="street" required value={addressDraft.street} onChange={e=>setAddressDraft({...addressDraft,street:e.target.value})}/></label><label>Número<input name="number" required/></label><label>Complemento<input name="complement"/></label><label>Bairro<input name="neighborhood" value={addressDraft.neighborhood} onChange={e=>setAddressDraft({...addressDraft,neighborhood:e.target.value})}/></label><label>Cidade<input name="city" required value={addressDraft.city} onChange={e=>setAddressDraft({...addressDraft,city:e.target.value})}/></label><label>Estado<input name="state" required maxLength={2} value={addressDraft.state} onChange={e=>setAddressDraft({...addressDraft,state:e.target.value.toUpperCase()})}/></label><label className="default-address"><input type="checkbox" name="isDefault" value="true"/> Usar como endereço principal</label><button>Salvar endereço</button></form>}<div className="address-list">{addresses.length?addresses.map(a=><div key={a.id}><MapPin/><span><b>{a.label}{a.isDefault?" • Principal":""}</b><small>{a.street}, {a.number}{a.complement&&` • ${a.complement}`}<br/>{a.neighborhood&&`${a.neighborhood} • `}{a.city}/{a.state} • {a.postalCode.replace(/(\d{5})(\d{3})/,"$1-$2")}</small></span><button onClick={()=>removeAddress(a.id)} aria-label={`Remover endereço ${a.label}`}><Trash2/></button></div>):<div className="account-empty-state"><MapPin/><b>Nenhum endereço salvo</b><p>Adicione um endereço para agilizar o checkout.</p></div>}</div></article>
    <article id="orders" className="account-card"><div className="account-card-head"><span><small>HISTÓRICO</small><h2>Minhas compras</h2></span></div>{orders.length?<div className="order-history">{orders.map(o=><div key={o.id}><span><b>#{o.id}</b><small>{new Date(o.createdAt.replace(" ","T")+"Z").toLocaleDateString("pt-BR")} • {o.itemCount} {o.itemCount===1?"item":"itens"}{o.vehiclePlate&&` • ${o.vehiclePlate}`}</small></span><strong>{money(o.totalCents)}</strong><em className={`status-${o.status}`}>{statusLabel[o.status]||o.status}</em></div>)}</div>:<div className="account-empty-state"><Package/><b>Nenhum pedido ainda</b><p>Quando você finalizar uma compra, o acompanhamento aparecerá aqui.</p><a href="/catalogo">Explorar catálogo</a></div>}</article>
  </section></main>
}
