"use client";

import { ArrowLeft, CheckCircle2, ChevronRight, CircleGauge, PackageCheck, ShieldCheck, ShoppingCart, Truck } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import StoreHeader from "../../store-header";

type Product={code:string;originalCode:string;product:string;application:string;axle:string;type:string;hub:string;priceCents:number|null;stockQuantity:number|null;imageUrl:string|null};
const money=(value:number)=>value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function ProductPage(){
  const {code}=useParams<{code:string}>(); const [product,setProduct]=useState<Product|null>(null); const [loading,setLoading]=useState(true); const [cartCount,setCartCount]=useState(0); const [added,setAdded]=useState(false); const [userName,setUserName]=useState<string|null>(null);
  useEffect(()=>{Promise.resolve().then(()=>setCartCount((JSON.parse(localStorage.getItem("highparts_cart")||"[]") as string[]).length));fetch("/api/auth/me").then(r=>r.json()).then(x=>setUserName(x.user?.name||null)).catch(()=>{});fetch(`/api/catalog/${encodeURIComponent(code)}`).then(r=>r.ok?r.json():Promise.reject()).then(x=>setProduct(x.product)).catch(()=>setProduct(null)).finally(()=>setLoading(false))},[code]);
  function add(){if(!product||product.priceCents==null||!product.stockQuantity)return;const cart=JSON.parse(localStorage.getItem("highparts_cart")||"[]") as string[];cart.push(product.code);localStorage.setItem("highparts_cart",JSON.stringify(cart));setCartCount(cart.length);setAdded(true)}
  if(loading)return <main className="product-page"><StoreHeader cartCount={cartCount}/><div className="product-loading">Carregando produto…</div></main>;
  if(!product)return <main className="product-page"><StoreHeader cartCount={cartCount}/><div className="product-not-found"><h1>Produto não encontrado.</h1><a href="/catalogo">Voltar ao catálogo</a></div></main>;
  const available=product.priceCents!=null&&product.stockQuantity!=null&&product.stockQuantity>0;
  return <main className="product-page"><StoreHeader userName={userName} cartCount={cartCount}/><div className="product-breadcrumb"><a href="/"><span>Início</span></a><ChevronRight/><a href="/catalogo"><span>Catálogo</span></a><ChevronRight/><b>{product.code}</b></div><section className="product-detail"><div className="product-gallery"><div className="product-render"><span>HIGHPARTS · {product.product}</span><div className="render-disc"/><div className="render-caliper">HP</div><b>{product.code}</b></div><small>Imagem ilustrativa. Confira as especificações e a aplicação.</small></div><div className="product-info"><a className="back-catalog" href="/catalogo"><ArrowLeft/> Voltar ao catálogo</a><small className="product-kicker">{product.product}</small><h1>{product.product}</h1><p className="product-code">Código HighParts <b>{product.code}</b>{product.originalCode&&<> · Referência <b>{product.originalCode}</b></>}</p><div className="fit-alert"><CheckCircle2/><span><b>Compatibilidade técnica disponível</b><small>Confira abaixo se o veículo, ano e versão correspondem ao seu carro.</small></span></div><div className="product-price-box">{available?<><strong>{money(product.priceCents!/100)}</strong><span>{product.stockQuantity} unidades disponíveis</span><button onClick={add}><ShoppingCart/>{added?"Adicionado ao carrinho":"Adicionar ao carrinho"}</button></>:<><strong>Consulte disponibilidade</strong><span>O administrador ainda não publicou preço e estoque.</span><button disabled>Indisponível no momento</button></>}</div><div className="product-assurances"><span><ShieldCheck/><b>Compra protegida</b></span><span><Truck/><b>Envio calculado no checkout</b></span></div></div></section><section className="product-specs"><div><small>APLICAÇÃO</small><h2>Serve no meu carro?</h2><p>{product.application}</p><a href="/#compatibilidade">Consultar pela placa <ChevronRight/></a></div><aside><small>DETALHES TÉCNICOS</small><Spec icon={<PackageCheck/>} label="Produto" value={product.product}/><Spec icon={<CircleGauge/>} label="Eixo" value={product.axle||"Não informado"}/><Spec icon={<PackageCheck/>} label="Tipo" value={product.type||"Não informado"}/><Spec icon={<CircleGauge/>} label="Cubo" value={product.hub||"Não informado"}/></aside></section></main>
}

function Spec({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="spec-row">{icon}<span><small>{label}</small><b>{value}</b></span></div>}
